[profile.default]
src = "src"
out = "out"
libs = ['lib']
solc = "0.8.26"
optimizer_runs = 1_000_000
bytecode_hash = "none"

[fmt]
line_length = 200
tab_width = 4
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = false
quote_style = "double"
number_underscore = "thousands"
